//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentFactory
{
    using System;
    using System.Collections.Generic;
    
    public partial class FurnitureType
    {
        public int IdFurnitureType { get; set; }
        public string IdFurniture { get; set; }
        public int IdType { get; set; }
    
        public virtual Furniture Furniture { get; set; }
        public virtual Type Type { get; set; }
    }
}
