//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentFactory
{
    using System;
    using System.Collections.Generic;
    
    public partial class FurnitureProduct
    {
        public string IdFurniture { get; set; }
        public string IdProduct { get; set; }
        public string Location { get; set; }
        public int Turn { get; set; }
        public Nullable<int> Count { get; set; }
    
        public virtual Furniture Furniture { get; set; }
        public virtual Product Product { get; set; }
    }
}
