//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentFactory
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int IdOrder { get; set; }
        public System.DateTime Date { get; set; }
        public string ExecutionStage { get; set; }
        public string IdCustomer { get; set; }
        public string IdManager { get; set; }
    
        public virtual CustomProduct CustomProduct { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
